# Generated by Django 5.0.1 on 2024-01-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('Description', models.TextField()),
                ('Certifications', models.CharField(choices=[('adult', 'A+'), ('under supervision', 'UA'), ('Universal', 'U')], max_length=100)),
            ],
        ),
    ]
